### ISSUE TITLE
Updating the plugin to 1.18

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Arthed-Plugins/Crawling#4]
In case you weren't aware already, the plugin does not appear to be working on 1.18.

[This is the error in the server console](https://www.toptal.com/developers/hastebin/pejarerawe.properties) that occurs when starting it with Crawling installed on PaperMC for 1.18.

Thank you!

**Comment by TheNickm2** [comment]
I've forked the repository and created a temporary fix for this particular issue. The plugin has hard-coded version compatibility, and when it doesn't recognize 1.18 as a supported version, it disables itself. I simply added 1.18 to the hard-coded versions. The modified version can be downloaded here: https://github.com/TheNickm2/Crawling/releases/tag/5.2.0

Please note that I didn't thoroughly test this, nor do I suggest using it on a production server. Additionally, this modified version should not be used once a proper update is released (at which point I will take this modified version down).

**Comment by Styro457** [comment]
Fixed
